/*
 * Final assembly: turn a plugin-sdk.json manifest into a single
 * self-contained TypeScript file with body types + a typed client.
 *
 * Output shape:
 *
 *   // banner + manifest hash
 *
 *   export interface SubmissionsCreateBody { ... }
 *
 *   export interface PluginSDKClient {
 *     submissions: {
 *       create(body: SubmissionsCreateBody): Promise<unknown>;
 *       get(params: { id: string | number }): Promise<unknown>;
 *     };
 *   }
 *
 *   export interface PluginSDKClientOptions {
 *     baseUrl: string;        // e.g. window.wpApiSettings.root
 *     nonce: string;          // e.g. window.wpApiSettings.nonce
 *     fetchImpl?: typeof fetch;
 *   }
 *
 *   export function createPluginSDKClient(opts: PluginSDKClientOptions): PluginSDKClient { ... }
 *
 * The emitted client uses native fetch + wp's _wpnonce header. Bring
 * your own fetch implementation (or `node-fetch` polyfill) on the
 * server side via the `fetchImpl` option.
 */

import { schemaToTs } from './schema-to-ts.ts';
import { deriveRouteName } from './route-names.ts';

interface ManifestRoute {
  path: string;
  method: string;
  schema?: Record<string, unknown>;
  capability?: string;
  handler?: string;
}

interface Manifest {
  name: string;
  slug: string;
  version?: string;
  rest?: {
    namespace: string;
    routes: ManifestRoute[];
  };
}

export interface EmitResult {
  /** Full TS source. */
  source: string;
  /** Number of routes emitted. */
  routeCount: number;
  /** Number of body type interfaces emitted. */
  bodyTypeCount: number;
}

export function emitClient(manifest: Manifest): EmitResult {
  const rest = manifest.rest;
  const ns = rest?.namespace ?? '';
  const routes = rest?.routes ?? [];

  const sections: string[] = [];

  sections.push(banner(manifest));

  // ── Body type interfaces ───────────────────────────────────────────
  // For every route that declares a `schema`, emit a named interface.
  // Routes without a schema fall back to `unknown` for their body arg.
  const namedRoutes = routes.map((r) => ({ ...r, name: deriveRouteName(r.method, r.path) }));
  const bodyTypes: string[] = [];
  for (const r of namedRoutes) {
    if (!r.schema) continue;
    const body = schemaToTs(r.schema as never);
    bodyTypes.push(`export interface ${r.name.bodyTypeName} ${body}`);
  }
  if (bodyTypes.length > 0) {
    sections.push(['// ── Request body types ───────────────────────────────', ...bodyTypes].join('\n'));
  }

  // ── Group routes by resource ───────────────────────────────────────
  const groups = new Map<string, typeof namedRoutes>();
  for (const r of namedRoutes) {
    const list = groups.get(r.name.group) ?? [];
    list.push(r);
    groups.set(r.name.group, list);
  }

  // ── Client interface ───────────────────────────────────────────────
  const clientLines: string[] = ['export interface PluginSDKClient {'];
  for (const [group, list] of groups) {
    clientLines.push(`  ${group}: {`);
    for (const r of list) {
      const params = methodParams(r);
      clientLines.push(`    ${r.name.verb}${params.signature}: Promise<unknown>;`);
    }
    clientLines.push(`  };`);
  }
  clientLines.push('}');
  sections.push(clientLines.join('\n'));

  // ── Client implementation ──────────────────────────────────────────
  sections.push(clientOptionsInterface());
  sections.push(createClientFn(ns, namedRoutes));

  return {
    source: sections.join('\n\n') + '\n',
    routeCount: routes.length,
    bodyTypeCount: bodyTypes.length,
  };
}

/* ── helpers ────────────────────────────────────────────────────────── */

function banner(manifest: Manifest): string {
  return [
    `/**`,
    ` * Auto-generated by @plugin-sdk/cli codegen.`,
    ` * Plugin: ${manifest.name} (${manifest.slug})`,
    manifest.version ? ` * Version: ${manifest.version}` : ``,
    ` *`,
    ` * Do not edit by hand. Regenerate with:`,
    ` *   npx @plugin-sdk/cli codegen`,
    ` *`,
    ` * Source of truth: plugin-sdk.json`,
    ` */`,
  ].filter(Boolean).join('\n');
}

interface MethodParams {
  /** "(body: SubmissionsCreateBody, params: { id: string })" */
  signature: string;
  /** Names of the positional args, for the implementation: ['body', 'params'] */
  paramNames: string[];
}

function methodParams(r: {
  method: string;
  schema?: Record<string, unknown>;
  name: { bodyTypeName: string; pathParams: string[] };
}): MethodParams {
  const args: string[] = [];
  const names: string[] = [];
  const hasBody = ['POST', 'PUT', 'PATCH'].includes(r.method.toUpperCase());

  if (r.name.pathParams.length > 0) {
    const pp = r.name.pathParams.map((n) => `${n}: string | number`).join('; ');
    args.push(`params: { ${pp} }`);
    names.push('params');
  }
  if (hasBody) {
    const t = r.schema ? r.name.bodyTypeName : 'unknown';
    args.push(`body: ${t}`);
    names.push('body');
  }
  return {
    signature: '(' + args.join(', ') + ')',
    paramNames: names,
  };
}

function clientOptionsInterface(): string {
  return [
    `export interface PluginSDKClientOptions {`,
    `  /** REST API root, e.g. window.wpApiSettings.root */`,
    `  baseUrl: string;`,
    `  /** WP REST nonce, e.g. window.wpApiSettings.nonce */`,
    `  nonce: string;`,
    `  /** Override fetch (Node, tests, custom transport). Defaults to globalThis.fetch. */`,
    `  fetchImpl?: typeof fetch;`,
    `}`,
  ].join('\n');
}

function createClientFn(
  restNamespace: string,
  routes: Array<{
    path: string;
    method: string;
    schema?: Record<string, unknown>;
    name: { group: string; verb: string; bodyTypeName: string; pathParams: string[] };
  }>,
): string {
  const lines: string[] = [];
  lines.push('export function createPluginSDKClient(opts: PluginSDKClientOptions): PluginSDKClient {');
  lines.push('  const fetchImpl: typeof fetch = opts.fetchImpl ?? globalThis.fetch.bind(globalThis);');
  lines.push('  const trimmed = opts.baseUrl.replace(/\\/+$/, \'\');');
  lines.push(`  const ns = ${JSON.stringify(restNamespace)};`);
  lines.push('');
  lines.push('  async function call(method: string, path: string, body?: unknown): Promise<unknown> {');
  lines.push('    const url = `${trimmed}/${ns}${path}`;');
  lines.push('    const init: RequestInit = {');
  lines.push('      method,');
  lines.push('      credentials: \'same-origin\',');
  lines.push('      headers: {');
  lines.push('        \'Content-Type\': \'application/json\',');
  lines.push('        \'X-WP-Nonce\': opts.nonce,');
  lines.push('      },');
  lines.push('    };');
  lines.push('    if (body !== undefined) init.body = JSON.stringify(body);');
  lines.push('    const res = await fetchImpl(url, init);');
  lines.push('    if (!res.ok) {');
  lines.push('      const text = await res.text();');
  lines.push('      throw new Error(`PluginSDK ${method} ${path} → ${res.status}: ${text}`);');
  lines.push('    }');
  lines.push('    return res.headers.get(\'content-type\')?.includes(\'application/json\')');
  lines.push('      ? res.json()');
  lines.push('      : res.text();');
  lines.push('  }');
  lines.push('');

  // group → methods
  const groups = new Map<string, typeof routes>();
  for (const r of routes) {
    const list = groups.get(r.name.group) ?? [];
    list.push(r);
    groups.set(r.name.group, list);
  }
  lines.push('  return {');
  for (const [group, list] of groups) {
    lines.push(`    ${group}: {`);
    for (const r of list) {
      const hasBody = ['POST', 'PUT', 'PATCH'].includes(r.method.toUpperCase());
      const params = r.name.pathParams.length > 0;
      const args: string[] = [];
      if (params) args.push('params');
      if (hasBody) args.push('body');

      // Path interpolation: replace (?P<id>...) with ${params.id}.
      const pathTemplate = renderPathTemplate(r.path);

      const bodyArg = hasBody ? ', body' : '';
      lines.push(`      ${r.name.verb}: (${args.map((a, i) => a === 'params' ? `params: { ${r.name.pathParams.map((p) => `${p}: string | number`).join('; ')} }` : `body: ${r.schema ? r.name.bodyTypeName : 'unknown'}`).join(', ')}) =>`);
      lines.push(`        call(${JSON.stringify(r.method.toUpperCase())}, ${pathTemplate}${bodyArg}),`);
    }
    lines.push(`    },`);
  }
  lines.push('  };');
  lines.push('}');
  return lines.join('\n');
}

/** Convert "/submissions/(?P<id>\\d+)/approve" → "`/submissions/${params.id}/approve`" */
function renderPathTemplate(path: string): string {
  const cleaned = path.replace(/\(\?P<([a-zA-Z_][a-zA-Z0-9_]*)>[^)]*\)/g, (_, name) => '${params.' + name + '}');
  if (cleaned === path) {
    // No interpolation needed; emit a plain string literal.
    return JSON.stringify(path);
  }
  return '`' + cleaned + '`';
}
